export const GET_TOP_ARTICLES = 'GET_TOP_ARTICLES'
export const NEXT_ARTICLES = 'NEXT_ARTICLES'
export const PREV_ARTICLES = 'PREV_ARTICLES'

export const GET_DETAIL_ARTICLE = 'GET_DETAIL_ARTICLE'

export const LOAD_ARTICLES_ERROR = 'LOAD_ARTICLES_ERROR'
export const LOAD_ARTICLES_LOADING = 'LOAD_ARTICLES_LOADING'
export const LOAD_ALL_ARTICLES_SUCCESS = 'LOAD_ALL_ARTICLES_SUCCESS'
