export const GET_ALL_ARTICLES = 'GET_ALL_ARTICLES'
export const GET_DETAIL_ARTICLE = 'GET_DETAIL_ARTICLE'
export const GET_ARTICLES_BY_CATEGORY = 'GET_ARTICLES_BY_CATEGORY'

export const GET_TOP_ARTICLES = 'GET_TOP_ARTICLES'
export const NEXT_ARTICLES = 'NEXT_ARTICLES'
export const PREV_ARTICLES = 'PREV_ARTICLES'